baseURL = 'https://stranaimir2023ru.sakharov.world'
languageCode = 'ru'
title = 'Страна и мир: российские реалии 2023'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false